const Actions = {
    FETCH_PRODUCTS: 'FETCH_PRODUCTS',
    FETCH_PRODUCTS_FOR_SEARCH_STRING: 'FETCH_PRODUCTS_FOR_SEARCH_STRING',
    OPEN_MODAL:'OPEN_MODAL',
    CLOSE_MODAL:'CLOSE_MODAL',
    SET_MODAL_TYPE:'SET_MODAL_TYPE',
    GET_CATEGORY:'GET_CATEGORY',
    FILTER_PRODUCTS:'FILTER_PRODUCTS',
    SET_PERPAGE:'SET_PERPAGE',
    SET_PAGES:'SET_PAGES',
    SET_CURRENT_PAGE:'SET_CURRENT_PAGE',
    SET_SEARCH_FILTERS:'SET_SEARCH_FILTERS',
    SET_SORT_PRODUCTS: 'SET_SORT_PRODUCTS',
    GET_ALL_CATALOG:'GET_ALL_CATALOG',
    FETCH_PRODUCTS_FAILED: 'FETCH_PRODUCTS_FAILED',
    SEARCH_CHANGE: 'SEARCH_CHANGE',
    SET_CURRENT_PRODUCT: 'SET_CURRENT_PRODUCT',
    SET_RECENTLY_VIEWED_PRODUCTS: 'SET_RECENTLY_VIEWED_PRODUCTS'
}

export default Actions;