const Actions = {
    FETCH_PRODUCTS: 'FETCH_PRODUCTS',
    GET_CATEGORY:'GET_CATEGORY',
    FILTER_PRODUCTS:'FILTER_PRODUCTS',
    SET_PERPAGE:'SET_PERPAGE',
    SET_PAGES:'SET_PAGES',
    SET_CURRENT_PAGE:'SET_CURRENT_PAGE',
    SET_SEARCH_FILTERS:'SET_SEARCH_FILTERS',
    SET_SORT_PRODUCTS: 'SET_SORT_PRODUCTS',
    GET_ALL_CATALOG:'GET_ALL_CATALOG'
}

export default Actions;